# Generated by Django 3.1.7 on 2021-03-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registrationRequest',
            fields=[
                ('proposedUsername', models.CharField(max_length=20)),
                ('proposedPassword', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='sspCredential',
            fields=[
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('emailAddress', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('emailAddress', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
