# Generated by Django 3.1.7 on 2021-03-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseNumber', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('courseTitle', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('sectionID', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
