# Generated by Django 3.1.7 on 2021-03-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('department_ID', models.CharField(max_length=4, verbose_name='Department ID')),
                ('course_Number', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Course Number')),
                ('course_Title', models.CharField(max_length=255, verbose_name='Course Title')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Time', models.TimeField(verbose_name='Start Time')),
                ('end_Time', models.TimeField(verbose_name='End Time')),
                ('meeting_day', models.CharField(choices=[('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F'), ('MW', 'MW'), ('MWF', 'MWF'), ('TR', 'TR'), ('MWTWRF', 'MWTWRF')], default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_ID', models.CharField(max_length=4, verbose_name='Section ID')),
                ('instructor', models.CharField(max_length=255, verbose_name='Instructor')),
                ('course_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
                ('periods', models.ManyToManyField(to='catalog.Period')),
            ],
        ),
    ]
