# Generated by Django 3.1.7 on 2021-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department_Number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='department_ID',
            field=models.CharField(default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_Time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_Time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_ID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
