# Generated by Django 3.1.7 on 2021-03-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210322_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course_Number',
        ),
    ]
