# Generated by Django 3.1.7 on 2021-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_course_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='classPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_days', models.CharField(blank=True, max_length=50)),
                ('time', models.TimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='courseTitle',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='department_ID',
            field=models.CharField(default='', max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='section',
            name='course_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(default=0),
        ),
    ]
