# Generated by Django 3.1.7 on 2021-03-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210316_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='classPeriod',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
