# Generated by Django 3.1.7 on 2021-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_auto_20210319_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentID', models.CharField(max_length=4, verbose_name='department ID')),
                ('courseNumber', models.CharField(max_length=4, verbose_name='course Number')),
            ],
        ),
    ]
