# Generated by Django 3.1.7 on 2021-03-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(default='', max_length=25, verbose_name='course Title'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionID', models.CharField(max_length=4, verbose_name='section ID')),
                ('instructor', models.CharField(max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('meetingDays', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('MW', 'Monday, Wednesday'), ('MWF', 'Monday, Wednesday, Friday'), ('TR', 'Tuesday, Thursday'), ('MTWRF', 'Monday, Tuesday, Wednesday, Thursday, Friday')], max_length=5)),
                ('sections', models.ManyToManyField(to='catalog.Section')),
            ],
        ),
    ]
