# Generated by Django 3.1.7 on 2021-03-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210319_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='periods',
            field=models.ManyToManyField(to='catalog.Period'),
        ),
    ]
