# Generated by Django 3.1.7 on 2021-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduleGenerator', '0002_delete_reservedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservedTime',
            fields=[
                ('description', models.CharField(blank=True, max_length=250)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('sectionID', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
